"""empty message

Revision ID: 0ec3a83a4b10
Revises: b32cd7046567
Create Date: 2021-04-19 20:57:58.831004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec3a83a4b10'
down_revision = 'b32cd7046567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'accountID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'fromID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'toID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'toID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'fromID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'accountID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
