"""empty message

Revision ID: 2849a01404f1
Revises: 3509477d63d8
Create Date: 2021-04-19 21:44:25.461570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2849a01404f1'
down_revision = '3509477d63d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userCode', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users', ['userCode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'userCode')
    # ### end Alembic commands ###
