"""empty message

Revision ID: b32cd7046567
Revises: ea84bcaf20f0
Create Date: 2021-04-19 20:54:29.036223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32cd7046567'
down_revision = 'ea84bcaf20f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fromID', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('toID', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_senderRecipientID_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['fromID'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['toID'], ['id'])
    op.drop_column('transactions', 'senderRecipientID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('senderRecipientID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_senderRecipientID_fkey', 'transactions', 'users', ['senderRecipientID'], ['id'])
    op.drop_column('transactions', 'toID')
    op.drop_column('transactions', 'fromID')
    # ### end Alembic commands ###
