"""empty message

Revision ID: c1e04dda6616
Revises: 72e3193b2267
Create Date: 2021-04-20 00:43:54.155507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e04dda6616'
down_revision = '72e3193b2267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_amount_key', 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transactions_amount_key', 'transactions', ['amount'])
    # ### end Alembic commands ###
