"""empty message

Revision ID: c206b46ee612
Revises: 7dc32b7b18ee
Create Date: 2021-04-19 19:59:19.946325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c206b46ee612'
down_revision = '7dc32b7b18ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('accountID', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_coinID_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['accountID'], ['id'])
    op.drop_column('transactions', 'coinID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('coinID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_coinID_fkey', 'transactions', 'coins', ['coinID'], ['id'])
    op.drop_column('transactions', 'accountID')
    # ### end Alembic commands ###
