"""empty message

Revision ID: ea84bcaf20f0
Revises: c206b46ee612
Create Date: 2021-04-19 20:29:16.366320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea84bcaf20f0'
down_revision = 'c206b46ee612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_balance_key', 'accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('accounts_balance_key', 'accounts', ['balance'])
    # ### end Alembic commands ###
